// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfh_ItlIdPoUH8e_N3vFtZVFctHWNvAD4',
    appId: '1:445785474881:web:58e534c253f457279f03c0',
    messagingSenderId: '445785474881',
    projectId: 'food-delivery-app-fc155',
    authDomain: 'food-delivery-app-fc155.firebaseapp.com',
    storageBucket: 'food-delivery-app-fc155.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXUftyw7Yy9HWqDH8uyqFZ238aTYClRa0',
    appId: '1:445785474881:android:9bb2900acbc64ade9f03c0',
    messagingSenderId: '445785474881',
    projectId: 'food-delivery-app-fc155',
    storageBucket: 'food-delivery-app-fc155.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQ-JLOqs16b-Qu_qVyJaloNNiMOSwy-U',
    appId: '1:445785474881:ios:74180a1b292fbd399f03c0',
    messagingSenderId: '445785474881',
    projectId: 'food-delivery-app-fc155',
    storageBucket: 'food-delivery-app-fc155.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALQ-JLOqs16b-Qu_qVyJaloNNiMOSwy-U',
    appId: '1:445785474881:ios:74180a1b292fbd399f03c0',
    messagingSenderId: '445785474881',
    projectId: 'food-delivery-app-fc155',
    storageBucket: 'food-delivery-app-fc155.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfh_ItlIdPoUH8e_N3vFtZVFctHWNvAD4',
    appId: '1:445785474881:web:6b3fb85d89b9de059f03c0',
    messagingSenderId: '445785474881',
    projectId: 'food-delivery-app-fc155',
    authDomain: 'food-delivery-app-fc155.firebaseapp.com',
    storageBucket: 'food-delivery-app-fc155.firebasestorage.app',
  );
}
